# Generated by Django 5.2.6 on 2025-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, choices=[('research_assistant', 'Research Assistant'), ('postdoctoral_researcher', 'Postdoctoral Researcher'), ('phd_student', 'PhD Student'), ('clinical_research_fellow', 'Clinical Research Fellow'), ('clinical_research_nurse', 'Clinical Research Nurse'), ('clinician_scientist', 'Clinician Scientist'), ('scientist', 'Scientist'), ('unknown', 'Unknown')], max_length=255, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_organisation',
            field=models.CharField(blank=True, choices=[('nhs_lothian', 'NHS Lothian'), ('nhs_ggc', 'NHS GGC'), ('nhs_tayside', 'NHS Tayside'), ('university_of_edinburgh', 'University of Edinburgh'), ('university_of_glasgow', 'University of Glasgow'), ('university_of_dundee', 'University of Dundee'), ('unknown', 'Unknown')], max_length=255, verbose_name='primary organisation'),
        ),
    ]
