site_name: Orca
site_url: "https://shaunchuah.github.io/musicsamples"
dev_addr: "127.0.0.1:8080"
theme:
  name: material

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
nav:
  - Home: index.md
  - Attribution Policy: attribution_policy.md
  - Dataset Governance: dataset_governance.md
  - Issues: issues.md
  - Data Dictionary:
      - data_dictionary/index.md
      - data_dictionary/abbreviations.md
      - data_dictionary/gidamps_columns.md
      - data_dictionary/music_columns.md
      - data_dictionary/mini_music_columns.md

  - Pipeline:
      - pipeline/index.md
      - pipeline/gidamps.md
      - pipeline/music.md
      - pipeline/mini_music.md
      - pipeline/combined_music.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
