[tool.djlint]
blank_line_after_tag = "load,extends"
close_void_tags = true
format_css = true
format_js = true
# TODO: remove T002 when fixed https://github.com/Riverside-Healthcare/djLint/issues/687
ignore = "H006,H030,H031,T002,D018"
include = "H017,H035"
indent = 2
max_line_length = 119
profile = "django"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.pytest.ini_options]
addopts = "--reuse-db --cov=. --cov-report term:skip-covered --cov-report=html"
DJANGO_SETTINGS_MODULE = "config.test_settings"
python_files = [
    "tests.py",
    "test_*.py",
]

[tool.ruff]
line-length = 119
target-version = 'py311'
exclude = [
    "venv/",
    "**/migrations/*.py",
    ]
