# Generated by Django 3.1.2 on 2020-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("musicsampleid", models.CharField(max_length=10)),
                ("patientid", models.CharField(max_length=30)),
                ("sample_location", models.CharField(max_length=200)),
                ("sample_type", models.CharField(max_length=200)),
                ("sample_datetime", models.DateTimeField()),
                ("sample_comments", models.TextField(blank=True, null=True)),
                ("created_by", models.CharField(max_length=200)),
                ("last_modified_by", models.CharField(max_length=200)),
                ("data_first_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
