# Generated by Django 5.1.4 on 2025-02-14 09:35

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('mini_marvel', 'Mini-MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200)),
                ('music_timepoint', models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('9_months', '9 Months'), ('12_months', '12 Months')], max_length=50, null=True)),
                ('marvel_timepoint', models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('12_weeks', '12 weeks'), ('24_weeks', '24 weeks')], max_length=50, null=True)),
                ('file_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.models.file_upload_path)),
                ('category', models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides')], max_length=200)),
                ('file_type', models.CharField(max_length=255)),
                ('original_file_name', models.TextField()),
                ('formatted_file_name', models.TextField()),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
                ('sample_id', models.ManyToManyField(blank=True, related_name='files', to='app.sample')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_finished_at'],
            },
        ),
    ]
