# Generated by Django 5.1.4 on 2025-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datastore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='file_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
