# Generated by Django 3.1.2 on 2020-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_historicalsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="sample_volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalsample",
            name="sample_volume_units",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_volume_units",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
