# Generated by Django 5.1.4 on 2025-02-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_datastore_sample_id_datastore_sample_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('study_name', models.CharField(blank=True, choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('mini_marvel', 'Mini-MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Study Identifier',
                'verbose_name_plural': 'Study Identifiers',
            },
        ),
        migrations.RemoveField(
            model_name='datastore',
            name='sample_id',
        ),
        migrations.AddField(
            model_name='historicalsample',
            name='study_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.studyidentifier'),
        ),
        migrations.AddField(
            model_name='sample',
            name='study_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='app.studyidentifier'),
        ),
    ]
