# Generated by Django 3.1.2 on 2020-11-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_auto_20201111_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="processing_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="processing_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
