# Generated by Django 5.1.4 on 2025-02-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transfer_patient_id_to_study_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyidentifier',
            options={'ordering': ['name'], 'verbose_name': 'Study Identifier', 'verbose_name_plural': 'Study Identifiers'},
        ),
        migrations.RemoveField(
            model_name='historicalsample',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='patient_id',
        ),
    ]
