# Generated by Django 5.1.4 on 2025-02-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_datastore_patient_id_datastore_study_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyidentifier',
            old_name='group',
            new_name='study_group_name',
        ),
        migrations.AddField(
            model_name='studyidentifier',
            name='study_center',
            field=models.CharField(blank=True, choices=[('edinburgh', 'Edinburgh'), ('glasgow', 'Glasgow'), ('dundee', 'Dundee')], max_length=200, null=True),
        ),
    ]
