# Generated by Django 5.1.4 on 2025-02-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_group_studyidentifier_study_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyidentifier',
            old_name='study_group_name',
            new_name='study_group',
        ),
    ]
