# Generated by Django 3.1.2 on 2021-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_historicalnote_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="sample_tags",
            field=models.ManyToManyField(blank=True, to="app.Sample"),
        ),
    ]
