# Generated by Django 5.1.4 on 2025-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_study_group_name_studyidentifier_study_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='sampling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyidentifier',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studyidentifier',
            name='study_center',
            field=models.CharField(blank=True, choices=[('edinburgh', 'Edinburgh'), ('glasgow', 'Glasgow'), ('dundee', 'Dundee'), ('aberdeen', 'Aberdeen')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studyidentifier',
            name='study_group',
            field=models.CharField(blank=True, choices=[('uc', 'UC'), ('cd', 'CD'), ('hc', 'HC'), ('ibdu', 'IBDU'), ('non_ibd', 'Non-IBD'), ('await_dx', 'Awaiting Diagnosis'), ('other', 'Other')], max_length=200, null=True),
        ),
    ]
