# Generated by Django 5.1.4 on 2025-02-28 15:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_datastore_sampling_date_alter_studyidentifier_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='study_name',
            field=models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalsample',
            name='study_name',
            field=models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='sample',
            name='study_name',
            field=models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studyidentifier',
            name='study_name',
            field=models.CharField(blank=True, choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalDataStore',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides')], max_length=200)),
                ('study_name', models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200)),
                ('music_timepoint', models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('9_months', '9 Months'), ('12_months', '12 Months')], max_length=50, null=True)),
                ('marvel_timepoint', models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('12_weeks', '12 weeks'), ('24_weeks', '24 weeks')], max_length=50, null=True)),
                ('sampling_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=255)),
                ('original_file_name', models.TextField(blank=True)),
                ('formatted_file_name', models.TextField(blank=True)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.studyidentifier')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical data store',
                'verbose_name_plural': 'historical data stores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudyIdentifier',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('study_name', models.CharField(blank=True, choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200, null=True)),
                ('study_center', models.CharField(blank=True, choices=[('edinburgh', 'Edinburgh'), ('glasgow', 'Glasgow'), ('dundee', 'Dundee'), ('aberdeen', 'Aberdeen')], max_length=200, null=True)),
                ('study_group', models.CharField(blank=True, choices=[('uc', 'UC'), ('cd', 'CD'), ('hc', 'HC'), ('ibdu', 'IBDU'), ('non_ibd', 'Non-IBD'), ('await_dx', 'Awaiting Diagnosis'), ('other', 'Other')], max_length=200, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Study Identifier',
                'verbose_name_plural': 'historical Study Identifiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
