# Generated by Django 5.1.4 on 2025-03-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_datastore_study_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastore',
            options={'ordering': ['-upload_finished_at'], 'permissions': (('delete_own_datastore', 'Can delete own datastore'),)},
        ),
    ]
