# Generated by Django 5.1.7 on 2025-03-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_datastore_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudyidentifier',
            name='genotype_data_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudyidentifier',
            name='il23r_mutation_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudyidentifier',
            name='nod2_mutation_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyidentifier',
            name='genotype_data_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyidentifier',
            name='il23r_mutation_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyidentifier',
            name='nod2_mutation_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='category',
            field=models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides'), ('fapi_pet_mri', 'FAPI PET MRI')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldatastore',
            name='category',
            field=models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides'), ('fapi_pet_mri', 'FAPI PET MRI')], max_length=200),
        ),
    ]
