# Generated by Django 5.1.7 on 2025-03-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_historicalstudyidentifier_genotype_data_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('crp', models.FloatField(blank=True, null=True)),
                ('calprotectin', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('study_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_data', to='app.studyidentifier')),
            ],
            options={
                'indexes': [models.Index(fields=['study_id', 'sample_date'], name='app_clinica_study_i_86c486_idx')],
                'unique_together': {('study_id', 'sample_date')},
            },
        ),
    ]
