# Generated by Django 5.1.7 on 2025-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_clinicaldata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicaldata',
            name='app_clinica_study_i_86c486_idx',
        ),
        migrations.AlterUniqueTogether(
            name='clinicaldata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='music_timepoint',
            field=models.CharField(blank=True, choices=[('baseline', 'Baseline'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('9_months', '9 Months'), ('12_months', '12 Months')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='sample_date',
            field=models.DateField(null=True),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.CheckConstraint(condition=models.Q(('sample_date__isnull', False), ('music_timepoint__isnull', False), _connector='OR'), name='clinical_data_has_date_or_timepoint'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.UniqueConstraint(condition=models.Q(('music_timepoint__isnull', True)), fields=('study_id', 'sample_date'), name='unique_study_id_sample_date'),
        ),
        migrations.AddConstraint(
            model_name='clinicaldata',
            constraint=models.UniqueConstraint(condition=models.Q(('sample_date__isnull', True)), fields=('study_id', 'music_timepoint'), name='unique_study_id_music_timepoint'),
        ),
    ]
