# Generated by Django 3.2.7 on 2021-10-13 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_auto_20211013_2345"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsample",
            old_name="data_first_created",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="data_first_created",
            new_name="created",
        ),
    ]
