# Generated by Django 3.2.7 on 2021-10-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_auto_20211013_2351"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsample",
            old_name="patientid",
            new_name="patient_id",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="patientid",
            new_name="patient_id",
        ),
    ]
