# Generated by Django 5.1.9 on 2025-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_clinicaldata_app_clinica_study_i_86c486_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_12_months',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endoscopic mucosal healing at 12 months'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_3_6_months',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endoscopic mucosal healing at 3-6 months'),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='category',
            field=models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides'), ('fapi_pet_mri', 'FAPI PET MRI'), ('spatial_transcriptomics', 'Spatial Transcriptomics')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldatastore',
            name='category',
            field=models.CharField(choices=[('uncategorised', 'Uncategorised'), ('endoscopy_videos', 'Endoscopy Videos'), ('histology_slides', 'Histology Slides'), ('fapi_pet_mri', 'FAPI PET MRI'), ('spatial_transcriptomics', 'Spatial Transcriptomics')], max_length=200),
        ),
    ]
