# Generated by Django 5.1.9 on 2025-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_clinicaldata_endoscopic_mucosal_healing_at_12_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_12_months',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_3_6_months',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
