# Generated by Django 5.1.9 on 2025-05-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_clinicaldata_endoscopic_mucosal_healing_at_12_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_12_months',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endoscopic mucosal healing at 12 months'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='endoscopic_mucosal_healing_at_3_6_months',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endoscopic mucosal healing at 3-6 months'),
        ),
    ]
