# Generated by Django 3.2.12 on 2022-02-02 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_auto_20220202_1634"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalnote",
            name="content",
        ),
        migrations.RemoveField(
            model_name="note",
            name="content",
        ),
    ]
