# Generated by Django 5.1.9 on 2025-09-12 12:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_clinicaldata_endoscopic_mucosal_healing_at_12_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicScienceSampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rna', 'RNA'), ('dna', 'DNA'), ('tissue', 'Tissue'), ('cells', 'Cells'), ('supernatants', 'Supernatants'), ('other', 'Other')], max_length=200, unique=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentalID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TissueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blood', 'Blood'), ('gut', 'Gut'), ('stool', 'Stool'), ('bone_marrow', 'Bone Marrow'), ('lung', 'Lung'), ('bronchoalveolar_lavage', 'Bronchoalveolar Lavage'), ('other', 'Other')], max_length=200, unique=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBasicScienceBox',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('basic_science_group', models.CharField(choices=[('bain', 'BAIN'), ('jones', 'JONES'), ('other', 'Other')], max_length=200)),
                ('box_id', models.CharField(db_index=True, max_length=200)),
                ('box_type', models.CharField(choices=[('basic_science_samples', 'Basic Science Samples'), ('basic_science_reagents', 'Basic Science Reagents')], max_length=200)),
                ('species', models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse')], max_length=100)),
                ('location', models.CharField(choices=[('sii_freezer_1', 'SII Freezer 1')], max_length=200)),
                ('row', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10, null=True)),
                ('column', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10, null=True)),
                ('depth', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical basic science box',
                'verbose_name_plural': 'historical basic science boxs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BasicScienceBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_science_group', models.CharField(choices=[('bain', 'BAIN'), ('jones', 'JONES'), ('other', 'Other')], max_length=200)),
                ('box_id', models.CharField(max_length=200, unique=True)),
                ('box_type', models.CharField(choices=[('basic_science_samples', 'Basic Science Samples'), ('basic_science_reagents', 'Basic Science Reagents')], max_length=200)),
                ('species', models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse')], max_length=100)),
                ('location', models.CharField(choices=[('sii_freezer_1', 'SII Freezer 1')], max_length=200)),
                ('row', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10, null=True)),
                ('column', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10, null=True)),
                ('depth', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boxes', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_boxes', to=settings.AUTH_USER_MODEL)),
                ('sample_types', models.ManyToManyField(related_name='boxes', to='app.basicsciencesampletype')),
                ('experimental_ids', models.ManyToManyField(related_name='boxes', to='app.experimentalid')),
                ('tissue_types', models.ManyToManyField(related_name='boxes', to='app.tissuetype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
