# Generated by Django 5.1.9 on 2025-09-12 12:57

from django.db import migrations
from app.choices import BasicScienceSampleTypeChoices, TissueTypeChoices


def preload_choices(apps, schema_editor):
    BasicScienceSampleType = apps.get_model('app', 'BasicScienceSampleType')
    TissueType = apps.get_model('app', 'TissueType')

    # Preload BasicScienceSampleType
    for choice_value, choice_label in BasicScienceSampleTypeChoices.choices:
        BasicScienceSampleType.objects.get_or_create(name=choice_value, label=choice_label)

    # Preload TissueType
    for choice_value, choice_label in TissueTypeChoices.choices:
        TissueType.objects.get_or_create(name=choice_value, label=choice_label)


def reverse_preload_choices(apps, schema_editor):
    BasicScienceSampleType = apps.get_model('app', 'BasicScienceSampleType')
    TissueType = apps.get_model('app', 'TissueType')

    # Delete the preloaded choices (only if not referenced)
    for choice_value, _ in BasicScienceSampleTypeChoices.choices:
        try:
            obj = BasicScienceSampleType.objects.get(name=choice_value)
            if not obj.boxes.exists():  # Check if not used in many-to-many
                obj.delete()
        except BasicScienceSampleType.DoesNotExist:
            pass

    for choice_value, _ in TissueTypeChoices.choices:
        try:
            obj = TissueType.objects.get(name=choice_value)
            if not obj.boxes.exists():
                obj.delete()
        except TissueType.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_basicsciencesampletype_experimentalid_tissuetype_and_more'),
    ]

    operations = [
        migrations.RunPython(preload_choices, reverse_preload_choices),
    ]
