# Generated by Django 5.0.6 on 2024-07-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_auto_20220207_1620"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsample",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical sample",
                "verbose_name_plural": "historical samples",
            },
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
