# Generated by Django 5.2.6 on 2025-09-17 21:20

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_load_basicsciencesampletype_tissuetype_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicsciencebox',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Basic Science Boxes'},
        ),
        migrations.AlterModelOptions(
            name='clinicaldata',
            options={'verbose_name_plural': 'Clinical Data'},
        ),
        migrations.AlterModelOptions(
            name='datastore',
            options={'ordering': ['-upload_finished_at'], 'permissions': (('delete_own_datastore', 'Can delete own datastore'),), 'verbose_name_plural': 'Data Stores'},
        ),
        migrations.AlterModelOptions(
            name='experimentalid',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Experimental IDs'},
        ),
        migrations.AlterModelOptions(
            name='historicalbasicsciencebox',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical basic science box', 'verbose_name_plural': 'historical Basic Science Boxes'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatastore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical data store', 'verbose_name_plural': 'historical Data Stores'},
        ),
        migrations.RemoveField(
            model_name='basicsciencebox',
            name='sample_types',
        ),
        migrations.RemoveField(
            model_name='basicsciencebox',
            name='tissue_types',
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experimental_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_modified_experimental_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='sample_types',
            field=models.ManyToManyField(blank=True, related_name='experimental_ids', to='app.basicsciencesampletype'),
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='tissue_types',
            field=models.ManyToManyField(blank=True, related_name='experimental_ids', to='app.tissuetype'),
        ),
        migrations.AlterField(
            model_name='basicsciencebox',
            name='box_type',
            field=models.CharField(choices=[('basic_science_samples', 'Samples'), ('basic_science_reagents', 'Reagents')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalbasicsciencebox',
            name='box_type',
            field=models.CharField(choices=[('basic_science_samples', 'Samples'), ('basic_science_reagents', 'Reagents')], max_length=200),
        ),
        migrations.CreateModel(
            name='HistoricalExperimentalID',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical experimental id',
                'verbose_name_plural': 'historical Experimental IDs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
