# Generated by Django 5.0.6 on 2024-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_alter_historicalsample_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="study_name",
            field=models.CharField(
                choices=[
                    ("gidamps", "GI-DAMPs"),
                    ("music", "MUSIC"),
                    ("mini_music", "Mini-MUSIC"),
                    ("marvel", "MARVEL"),
                    ("mini_marvel", "Mini-MARVEL"),
                    ("none", "None"),
                ],
                max_length=200,
                default="none",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sample",
            name="study_name",
            field=models.CharField(
                choices=[
                    ("gidamps", "GI-DAMPs"),
                    ("music", "MUSIC"),
                    ("mini_music", "Mini-MUSIC"),
                    ("marvel", "MARVEL"),
                    ("mini_marvel", "Mini-MARVEL"),
                    ("none", "None"),
                ],
                max_length=200,
                default="none",
            ),
            preserve_default=False,
        ),
    ]
