# Generated by Django 5.2.6 on 2025-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_basicsciencebox_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsciencebox',
            name='species',
        ),
        migrations.RemoveField(
            model_name='historicalbasicsciencebox',
            name='species',
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse')], default='mouse', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalexperimentalid',
            name='species',
            field=models.CharField(choices=[('human', 'Human'), ('mouse', 'Mouse')], default='mouse', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicsciencesampletype',
            name='name',
            field=models.CharField(choices=[('rna', 'RNA'), ('dna', 'DNA'), ('tissue', 'Tissue'), ('cells', 'Cells'), ('supernatants', 'Supernatants'), ('oct_compound', 'OCT Compound'), ('other', 'Other')], max_length=200, unique=True),
        ),
    ]
