# Generated by Django 5.2.6 on 2025-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_basicsciencebox_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentalid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexperimentalid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
