# Generated by Django 5.0.6 on 2024-07-20 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0025_populate_study_name_from_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsample",
            name="is_marvel_study",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="is_marvel_study",
        ),
    ]
