# Generated by Django 5.2.6 on 2025-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_experimentalid_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicsciencebox',
            name='basic_science_group',
        ),
        migrations.RemoveField(
            model_name='historicalbasicsciencebox',
            name='basic_science_group',
        ),
        migrations.AddField(
            model_name='experimentalid',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'BAIN'), ('jones', 'JONES'), ('other', 'Other')], default='jones', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalexperimentalid',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'BAIN'), ('jones', 'JONES'), ('other', 'Other')], default='jones', max_length=200),
            preserve_default=False,
        ),
    ]
