# Generated by Django 5.0.6 on 2024-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_remove_historicalsample_is_marvel_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sample",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
