# Generated by Django 5.2.6 on 2025-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_basicsciencebox_basic_science_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentalid',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'Bain'), ('jones', 'Jones'), ('ho', 'Ho'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalexperimentalid',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'Bain'), ('jones', 'Jones'), ('ho', 'Ho'), ('other', 'Other')], max_length=200),
        ),
    ]
