# Generated by Django 5.2.6 on 2025-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_experimentalid_basic_science_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentalid',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalexperimentalid',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='experimentalid',
            unique_together={('basic_science_group', 'name')},
        ),
    ]
