# Generated by Django 5.0.6 on 2024-07-21 13:41

from django.db import migrations
from django.db.models import Q


def forwards(apps, _):
    Sample = apps.get_model("app", "Sample")
    samples = Sample.objects.filter(Q(is_fully_used=True) | Q(is_deleted=True))
    for sample in samples:
        sample.is_used = True
        sample.save()

    HistoricalSample = apps.get_model("app", "HistoricalSample")
    historical_samples = HistoricalSample.objects.filter(
        Q(is_fully_used=True) | Q(is_deleted=True)
    )
    for historical_sample in historical_samples:
        historical_sample.is_used = True
        historical_sample.save()


def backwards(apps, _):
    Sample = apps.get_model("app", "Sample")
    samples = Sample.objects.filter(is_used=True)
    for sample in samples:
        sample.is_used = False
        sample.save()

    HistoricalSample = apps.get_model("app", "HistoricalSample")
    historical_samples = HistoricalSample.objects.filter(is_used=True)
    for historical_sample in historical_samples:
        historical_sample.is_used = False
        historical_sample.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_historicalsample_is_used_sample_is_used"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
