# Generated by Django 5.0.6 on 2024-07-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_historicalsample_is_fully_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsample",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="is_deleted",
        ),
    ]
