# Generated by Django 5.0.6 on 2024-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0031_historicalsample_music_timepoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsample",
            name="music_timepoint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baseline", "Baseline"),
                    ("3_months", "3 Months"),
                    ("6_months", "6 Months"),
                    ("9_months", "9 Months"),
                    ("12_months", "12 Months"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="music_timepoint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baseline", "Baseline"),
                    ("3_months", "3 Months"),
                    ("6_months", "6 Months"),
                    ("9_months", "9 Months"),
                    ("12_months", "12 Months"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
