# Generated by Django 5.2.9 on 2026-01-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_experiment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsciencebox',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'Bain'), ('jones', 'Jones'), ('ho', 'Ho'), ('other', 'Other')], default='jones', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalbasicsciencebox',
            name='basic_science_group',
            field=models.CharField(choices=[('bain', 'Bain'), ('jones', 'Jones'), ('ho', 'Ho'), ('other', 'Other')], default='jones', max_length=200),
        ),
    ]
