# Generated by Django 5.0.6 on 2024-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_historicalsample_qubit_cfdna_ng_ul_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="marvel_timepoint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baseline", "Baseline"),
                    ("12_weeks", "12 weeks"),
                    ("24_weeks", "24 weeks"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="marvel_timepoint",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baseline", "Baseline"),
                    ("12_weeks", "12 weeks"),
                    ("24_weeks", "24 weeks"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
