# Generated by Django 5.0.6 on 2024-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0034_historicalsample_marvel_timepoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsample",
            name="biopsy_inflamed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inflamed", "Inflamed"),
                    ("uninflamed", "Uninflamed"),
                    ("healthy", "Healthy"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="biopsy_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("terminal_ileum", "Terminal ileum"),
                    ("caecum", "Caecum"),
                    ("ascending", "Ascending colon"),
                    ("transverse", "Transverse colon"),
                    ("descending", "Descending colon"),
                    ("sigmoid", "Sigmoid colon"),
                    ("rectum", "Rectum"),
                    ("right_colon", "Right colon"),
                    ("left_colon", "Left colon"),
                    ("oesophagus", "Oesophagus"),
                    ("stomach", "Stomach"),
                    ("duodenum", "Duodenum"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="haemolysis_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Minimal"),
                    ("20", "20 mg/dL"),
                    ("50", "50 mg/dL"),
                    ("100", "100 mg/dL (unusable)"),
                    ("250", "250 mg/dL (unusable)"),
                    ("500", "500 mg/dL (unsuable)"),
                    ("1000", "1000mg/dL (unusable)"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("standard_edta", "Standard EDTA tube"),
                    ("edta_plasma", "EDTA plasma child aliquot"),
                    ("cfdna_tube", "PaxGene cfDNA tube"),
                    ("cfdna_plasma", "cfDNA plasma"),
                    ("cfdna_extracted", "Extracted cfDNA"),
                    ("paxgene_rna", "PaxGene RNA tube"),
                    ("rna_plasma", "PaxGene RNA child aliquot"),
                    ("standard_gel", "Standard gel tube"),
                    ("serum", "Serum"),
                    ("biopsy_formalin", "Formalin biopsy"),
                    ("biopsy_rnalater", "RNAlater biopsy"),
                    ("stool_standard", "Standard stool"),
                    ("stool_calprotectin", "Calprotectin"),
                    ("stool_qfit", "qFIT"),
                    ("stool_omnigut", "OmniGut"),
                    ("stool_supernatant", "Stool supernatant"),
                    ("saliva", "Saliva"),
                    ("paraffin_block", "Paraffin block"),
                    ("other", "Other - please specify in comments"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="biopsy_inflamed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inflamed", "Inflamed"),
                    ("uninflamed", "Uninflamed"),
                    ("healthy", "Healthy"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="biopsy_location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("terminal_ileum", "Terminal ileum"),
                    ("caecum", "Caecum"),
                    ("ascending", "Ascending colon"),
                    ("transverse", "Transverse colon"),
                    ("descending", "Descending colon"),
                    ("sigmoid", "Sigmoid colon"),
                    ("rectum", "Rectum"),
                    ("right_colon", "Right colon"),
                    ("left_colon", "Left colon"),
                    ("oesophagus", "Oesophagus"),
                    ("stomach", "Stomach"),
                    ("duodenum", "Duodenum"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="haemolysis_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Minimal"),
                    ("20", "20 mg/dL"),
                    ("50", "50 mg/dL"),
                    ("100", "100 mg/dL (unusable)"),
                    ("250", "250 mg/dL (unusable)"),
                    ("500", "500 mg/dL (unsuable)"),
                    ("1000", "1000mg/dL (unusable)"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("standard_edta", "Standard EDTA tube"),
                    ("edta_plasma", "EDTA plasma child aliquot"),
                    ("cfdna_tube", "PaxGene cfDNA tube"),
                    ("cfdna_plasma", "cfDNA plasma"),
                    ("cfdna_extracted", "Extracted cfDNA"),
                    ("paxgene_rna", "PaxGene RNA tube"),
                    ("rna_plasma", "PaxGene RNA child aliquot"),
                    ("standard_gel", "Standard gel tube"),
                    ("serum", "Serum"),
                    ("biopsy_formalin", "Formalin biopsy"),
                    ("biopsy_rnalater", "RNAlater biopsy"),
                    ("stool_standard", "Standard stool"),
                    ("stool_calprotectin", "Calprotectin"),
                    ("stool_qfit", "qFIT"),
                    ("stool_omnigut", "OmniGut"),
                    ("stool_supernatant", "Stool supernatant"),
                    ("saliva", "Saliva"),
                    ("paraffin_block", "Paraffin block"),
                    ("other", "Other - please specify in comments"),
                ],
                max_length=200,
            ),
        ),
    ]
