# Generated by Django 5.0.6 on 2024-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0035_alter_historicalsample_biopsy_inflamed_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsample",
            name="paraffin_block_key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="paraffin_block_key",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("standard_edta", "Standard EDTA tube"),
                    ("edta_plasma", "EDTA plasma child aliquot"),
                    ("cfdna_tube", "PaxGene cfDNA tube"),
                    ("cfdna_plasma", "PaxGene cfDNA plasma"),
                    ("cfdna_extracted", "Extracted cfDNA"),
                    ("paxgene_rna", "PaxGene RNA tube"),
                    ("rna_plasma", "PaxGene RNA child aliquot"),
                    ("standard_gel", "Standard gel tube"),
                    ("serum", "Serum"),
                    ("biopsy_formalin", "Formalin biopsy"),
                    ("biopsy_rnalater", "RNAlater biopsy"),
                    ("stool_standard", "Standard stool"),
                    ("stool_calprotectin", "Calprotectin"),
                    ("stool_qfit", "qFIT"),
                    ("stool_omnigut", "OmniGut"),
                    ("stool_supernatant", "Stool supernatant"),
                    ("saliva", "Saliva"),
                    ("paraffin_block", "Paraffin block"),
                    ("other", "Other - please specify in comments"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsample",
            name="sample_volume_units",
            field=models.CharField(
                blank=True,
                choices=[("ml", "ml"), ("ul", "ul")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                choices=[
                    ("standard_edta", "Standard EDTA tube"),
                    ("edta_plasma", "EDTA plasma child aliquot"),
                    ("cfdna_tube", "PaxGene cfDNA tube"),
                    ("cfdna_plasma", "PaxGene cfDNA plasma"),
                    ("cfdna_extracted", "Extracted cfDNA"),
                    ("paxgene_rna", "PaxGene RNA tube"),
                    ("rna_plasma", "PaxGene RNA child aliquot"),
                    ("standard_gel", "Standard gel tube"),
                    ("serum", "Serum"),
                    ("biopsy_formalin", "Formalin biopsy"),
                    ("biopsy_rnalater", "RNAlater biopsy"),
                    ("stool_standard", "Standard stool"),
                    ("stool_calprotectin", "Calprotectin"),
                    ("stool_qfit", "qFIT"),
                    ("stool_omnigut", "OmniGut"),
                    ("stool_supernatant", "Stool supernatant"),
                    ("saliva", "Saliva"),
                    ("paraffin_block", "Paraffin block"),
                    ("other", "Other - please specify in comments"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_volume_units",
            field=models.CharField(
                blank=True,
                choices=[("ml", "ml"), ("ul", "ul")],
                max_length=30,
                null=True,
            ),
        ),
    ]
