# Generated by Django 5.0.8 on 2024-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_historicalsample_paraffin_block_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsample',
            name='sample_type',
            field=models.CharField(choices=[('standard_edta', 'Standard EDTA tube'), ('edta_plasma', 'EDTA plasma child aliquot'), ('cfdna_tube', 'PaxGene cfDNA tube'), ('cfdna_plasma', 'PaxGene cfDNA plasma'), ('cfdna_extracted', 'Extracted cfDNA'), ('paxgene_rna', 'PaxGene RNA tube'), ('rna_plasma', 'PaxGene RNA child aliquot'), ('standard_gel', 'Standard gel tube'), ('serum', 'Serum'), ('biopsy_formalin', 'Formalin biopsy'), ('biopsy_rnalater', 'RNAlater biopsy'), ('paraffin_block', 'Paraffin block'), ('stool_standard', 'Standard stool'), ('stool_calprotectin', 'Calprotectin'), ('stool_qfit', 'qFIT'), ('stool_omnigut', 'OmniGut'), ('stool_supernatant', 'Stool supernatant'), ('saliva', 'Saliva'), ('other', 'Other - please specify in comments')], max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalsample',
            name='study_name',
            field=models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('mini_marvel', 'Mini-MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('standard_edta', 'Standard EDTA tube'), ('edta_plasma', 'EDTA plasma child aliquot'), ('cfdna_tube', 'PaxGene cfDNA tube'), ('cfdna_plasma', 'PaxGene cfDNA plasma'), ('cfdna_extracted', 'Extracted cfDNA'), ('paxgene_rna', 'PaxGene RNA tube'), ('rna_plasma', 'PaxGene RNA child aliquot'), ('standard_gel', 'Standard gel tube'), ('serum', 'Serum'), ('biopsy_formalin', 'Formalin biopsy'), ('biopsy_rnalater', 'RNAlater biopsy'), ('paraffin_block', 'Paraffin block'), ('stool_standard', 'Standard stool'), ('stool_calprotectin', 'Calprotectin'), ('stool_qfit', 'qFIT'), ('stool_omnigut', 'OmniGut'), ('stool_supernatant', 'Stool supernatant'), ('saliva', 'Saliva'), ('other', 'Other - please specify in comments')], max_length=200),
        ),
        migrations.AlterField(
            model_name='sample',
            name='study_name',
            field=models.CharField(choices=[('gidamps', 'GI-DAMPs'), ('music', 'MUSIC'), ('mini_music', 'Mini-MUSIC'), ('marvel', 'MARVEL'), ('mini_marvel', 'Mini-MARVEL'), ('fate_cd', 'FATE-CD'), ('none', 'None')], max_length=200),
        ),
    ]
